//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopQuanAo_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_TIET_SP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHI_TIET_SP()
        {
            this.CHI_TIET_DON_HANG = new HashSet<CHI_TIET_DON_HANG>();
            this.GIO_HANG = new HashSet<GIO_HANG>();
        }
    
        public string MaCTSP { get; set; }
        public string MaSP { get; set; }
        public string MaKichThuoc { get; set; }
        public decimal GiaBan { get; set; }
        public int SoLuong { get; set; }
        public bool TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHI_TIET_DON_HANG> CHI_TIET_DON_HANG { get; set; }
        public virtual KICH_THUOC KICH_THUOC { get; set; }
        public virtual SAN_PHAM SAN_PHAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIO_HANG> GIO_HANG { get; set; }
    }
}
