//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopQuanAo_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_TIET_DON_HANG
    {
        public string MaDonHang { get; set; }
        public string MaCTSP { get; set; }
        public int SoLuong { get; set; }
        public decimal DonGia { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual CHI_TIET_SP CHI_TIET_SP { get; set; }
        public virtual DON_HANG DON_HANG { get; set; }
    }
}
