//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopQuanAo_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANH_GIA
    {
        public string MaDanhGia { get; set; }
        public string MaSP { get; set; }
        public string MaKH { get; set; }
        public string TenKhachHang { get; set; }
        public int SoSao { get; set; }
        public string NoiDung { get; set; }
        public bool TrangThai { get; set; }
    
        public virtual KHACH_HANG KHACH_HANG { get; set; }
        public virtual SAN_PHAM SAN_PHAM { get; set; }
    }
}
