//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopQuanAo_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DON_HANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DON_HANG()
        {
            this.CHI_TIET_DON_HANG = new HashSet<CHI_TIET_DON_HANG>();
        }
    
        public string MaDonHang { get; set; }
        public string MaKH { get; set; }
        public string MaNV { get; set; }
        public string TenNguoiNhan { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public string MaCode { get; set; }
        public string MaPTVC { get; set; }
        public System.DateTime NgayDat { get; set; }
        public Nullable<System.DateTime> NgayGiaoDuKien { get; set; }
        public string DiaChiGiao { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> TongSoLuong { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<decimal> GiamGia { get; set; }
        public Nullable<decimal> PhiVanChuyen { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public string PhuongThucThanhToan { get; set; }
        public Nullable<bool> DaThanhToan { get; set; }
        public string TrangThaiDonHang { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHI_TIET_DON_HANG> CHI_TIET_DON_HANG { get; set; }
        public virtual KHACH_HANG KHACH_HANG { get; set; }
        public virtual MA_GIAM_GIA MA_GIAM_GIA { get; set; }
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
        public virtual PHUONG_THUC_VAN_CHUYEN PHUONG_THUC_VAN_CHUYEN { get; set; }
    }
}
