//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopQuanAo_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIO_HANG
    {
        public string MaKH { get; set; }
        public string MaCTSP { get; set; }
        public int SoLuong { get; set; }
    
        public virtual CHI_TIET_SP CHI_TIET_SP { get; set; }
        public virtual KHACH_HANG KHACH_HANG { get; set; }
    }
}
