//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopQuanAo_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HINH_ANH_SP
    {
        public string MaHinhAnh { get; set; }
        public string MaSP { get; set; }
        public string DuongDan { get; set; }
        public bool LaAnhChinh { get; set; }
        public bool TrangThai { get; set; }
    
        public virtual SAN_PHAM SAN_PHAM { get; set; }
    }
}
