//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopQuanAo_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_GIAM_GIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MA_GIAM_GIA()
        {
            this.DON_HANG = new HashSet<DON_HANG>();
        }
    
        public string MaCode { get; set; }
        public decimal GiaTri { get; set; }
        public string LoaiGiamGia { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public bool TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DON_HANG> DON_HANG { get; set; }
    }
}
